openapi: 3.0.3
info:
  title: Sample API
  version: 0.1.0
paths:
  /books:
    $ref: ./features/reading-recorder/books.yaml#/paths/~1books
  /users:
    $ref: ./features/common/users.yaml#/paths/~1users
